### ISSUE TITLE
Completed Assignment 3

### ISSUE THREAD

**Issue by OTeeEnabor** [ds4owd-001/md-03-assignments-OTeeEnabor#1]
@mianzg 
@larnsce 
@sskorik01

**Comment by larnsce** [comment]
Great job, @OTeeEnabor! You can see a comparison of what was deleted/edited (red - left side) and was added (green - right side) here: https://github.com/ds4owd-001/md-03-assignments-OTeeEnabor/commit/f7a56ac65c4f0437e8dd5a4a554535cd6840a780

I have added some comments:

- https://github.com/ds4owd-001/md-03-assignments-OTeeEnabor/commit/f7a56ac65c4f0437e8dd5a4a554535cd6840a780#r132725609.
- https://github.com/ds4owd-001/md-03-assignments-OTeeEnabor/commit/f7a56ac65c4f0437e8dd5a4a554535cd6840a780#r132725814
- https://github.com/ds4owd-001/md-03-assignments-OTeeEnabor/commit/f7a56ac65c4f0437e8dd5a4a554535cd6840a780#r132725841

On each line, one can add comments. A bit like you would do in MS Word with comments and track changes.

I will close the issue for you now
